

default-messages-paths:
  new-room-info-path: /room/new/info

codenames-game:
  min-room-id: 100000
  max-room-id: 1000000


codenames-words:
  resources-path: codenames-domain/src/main/resources/
  file-name: game-words-
