

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codenames
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true



codenames:
  words:
    resources-path: "${RESOURCES_PATH:codenames-domain/src/main/resources/}"
    file-prefix: "${FILE_PREFIX:game-words-}"


  game-rooms:
    min-room-id: "${MIN_ROOM_ID:100000}"
    max-room-id: "${MAX_ROOM_ID:1000000}"


  ws-response-paths:
    new-room-info-path: "${NEW_ROOM_INFO_PATH:/room/new/info}"


  rest-controller:
    cross-origin:
      - http://localhost:3000


  redis:
    user-room-sessions-hash-key: "${USER_ROOM_SESSIONS_HASH_KEY:user_room_sessions}"


  security:
    jwt: "${JWT:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9}"
