

codenames:
  words:
    resources-path: codenames-domain/src/main/resources/
    file-name: game-words-

  game-rooms:
    min-room-id: 100000
    max-room-id: 1000000

  ws-response-paths:
    new-room-info-path: /room/new/info

  rest-controller:
    cross-origin:
      - http://localhost:3000

  redis:
    user-room-sessions-hash-key: user_room_sessions


security:
  jwt: I don't understand this stupid thing.

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codenames
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
